<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>CryptoProExport.Core</AssemblyName>
    <RootNamespace>CryptoProExport</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
